version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "com.google.guava:guava"
      - dependency-name: "com.fasterxml.jackson.core:*"
      - dependency-name: "io.netty:*"
      - dependency-name: "org.apache.logging.log4j:*"
      - dependency-name: "org.slf4j:*"
